version: '3.3'

#host.docker.internal db host for grafana

#`docker volume create --name=grafana-storage

volumes:
  grafana-storage:
    external: true

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: workshop_prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    expose:
      - 9090
    ports:
      - 9090:9090
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 750M

  #  admin/admin
  grafana:
    image: grafana/grafana:latest
    container_name: workshop_grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    links:
      - prometheus:prometheus
    expose:
      - 3000
    ports:
      - 3000:3000




