global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - rules.yml


scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']

  - job_name: 'metrics-actuator'
    metrics_path: '/metrics/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8080'] #setLocalIP
